MetaVer: 1
Name: STRAWBERRY GODZILLA
Artists:
  - Sugar&Co.
Creators:
  - Rainbow Dash
  - ESV zeph
Mirrors:
  - Name: MeowcaTheoRange
    URL: https://abtmtr.link/
Sources:
  - Name: Quaver
    URL: https://quavergame.com/
Tags:
  - Pop
  - Electronic
  - C-Pop
  - Vocal
AudioFile: audio.mp3
Maps:
  - maps/insane.yaml
Description: This is a VCRG converted version of Quaver's ESVT24 wackiness.
