MetaVer: 1
Name: Princess of Winter
Artists:
  - HyuN
Creators:
  - PianoLuigi
Mirrors:
  - Name: MeowcaTheoRange
    URL: https://abtmtr.link/
Sources:
  - Name: Quaver
    URL: https://quavergame.com/
Tags:
  - J-core
  - Electronic
  - Instumental
AudioFile: audio.mp3
Maps:
  - maps/insane.yaml
Description: This is a VCRG converted version of a Quaver converted version of PianoLuigi's map.
